New log file opened at Sun May 03 15:10:14 CEST 2015 by 6808@Dave-PC
Taking next connection to: 64806
New client attempting to connect on port: 64807-64806
  Address = /169.254.80.80:64806
This client on port 64807 has uuid 1f8994e4-3b70-4366-9d12-ac92e26333d6 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-1f8994e4-3b70-4366-9d12-ac92e26333d6
Taking next connection to: 64806
New client attempting to connect on port: 65030-64806
  Address = /169.254.80.80:64806
Handshake exception on socket: 65030
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 64806
New client attempting to connect on port: 65031-64806
  Address = /169.254.80.80:64806
This client on port 65031 has uuid f429fc20-28c1-4254-a2fa-b842700335ea configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-1f8994e4-3b70-4366-9d12-ac92e26333d6, play-fork-run-f429fc20-28c1-4254-a2fa-b842700335ea
Taking next connection to: 64806
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 64806
New client attempting to connect on port: 65108-64806
  Address = /169.254.80.80:64806
Handshake exception on socket: 65108
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 64806
New client attempting to connect on port: 65109-64806
  Address = /169.254.80.80:64806
This client on port 65109 has uuid 4829968e-0382-4b98-8c64-4192ea67950c configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-1f8994e4-3b70-4366-9d12-ac92e26333d6, play-fork-run-4829968e-0382-4b98-8c64-4192ea67950c
Taking next connection to: 64806
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 64806
New client attempting to connect on port: 65160-64806
  Address = /169.254.80.80:64806
Handshake exception on socket: 65160
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 64806
New client attempting to connect on port: 65161-64806
  Address = /169.254.80.80:64806
This client on port 65161 has uuid ce5ff816-bbde-442d-85b6-da3e83c1c259 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-1f8994e4-3b70-4366-9d12-ac92e26333d6, play-fork-run-ce5ff816-bbde-442d-85b6-da3e83c1c259
Taking next connection to: 64806
New client attempting to connect on port: 65225-64806
  Address = /169.254.80.80:64806
Handshake exception on socket: 65225
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 64806
New client attempting to connect on port: 65226-64806
  Address = /169.254.80.80:64806
This client on port 65226 has uuid 1db908af-597e-43d1-af7f-607428a5a5ba configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-1f8994e4-3b70-4366-9d12-ac92e26333d6, play-fork-run-1db908af-597e-43d1-af7f-607428a5a5ba
Taking next connection to: 64806
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 64806
